version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: expense_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  expense-app:
    build: .
    container_name: expense_app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/expenses
      PORT: 8080
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

  # Optional: node-exporter (if you want to monitor container/host)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

volumes:
  pgdata:
